import { Notice, PageHeader, SectionHeading, StatusChip } from "@/components/product-ui";
import { SubmitButton } from "@/components/submit-button";
import { listInvitations, listWorkspaceMembers } from "@/lib/db";
import { inviteMemberAction, removeMemberAction, revokeInvitationAction, updateMemberRoleAction } from "../_actions";
import { canAdminister, getDashboardContext } from "../_context";

export const metadata = { title: "Team" };
const roles = ["owner", "admin", "analyst", "viewer"] as const;

export default async function TeamPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [ctx, query] = await Promise.all([getDashboardContext(), searchParams]);
  const admin = canAdminister(ctx.actor.role);
  const [members, invitations] = await Promise.all([listWorkspaceMembers(ctx), admin ? listInvitations(ctx) : Promise.resolve([])]);
  return <>
    <PageHeader eyebrow="Team and access" title="Give each role only what it needs." description="Membership and role are checked on every repository mutation; privileged controls are rendered only for authorized roles." />
    {query.saved ? <Notice title="Saved" tone="info"><p>{query.saved}</p></Notice> : null}
    {query.error ? <Notice title="Team change failed" tone="critical"><p>{query.error}</p></Notice> : null}
    {admin ? <section className="workspace-card"><SectionHeading title="Invite member" description="The invitation is stored before a secure mailbox link is sent. It expires after 72 hours." /><form action={inviteMemberAction} className="inline-action-form"><label htmlFor="invite-email">Email</label><input id="invite-email" name="email" type="email" autoComplete="email" required /><label htmlFor="invite-role">Role</label><select id="invite-role" name="role"><option value="viewer">Viewer</option><option value="analyst">Analyst</option><option value="admin">Admin</option>{ctx.actor.role === "owner" ? <option value="owner">Owner</option> : null}</select><SubmitButton pendingLabel="Sending…">Send invitation</SubmitButton></form></section> : <Notice title="Member administration is restricted" tone="info"><p>Your {ctx.actor.role} role can inspect the roster but cannot invite or manage members.</p></Notice>}
    <section className="workspace-card workspace-section-spaced"><SectionHeading title="Workspace members" description={`${members.length} verified membership record${members.length === 1 ? "" : "s"}. Email/profile lookup is not part of the repository contract.`} /><div className="table-wrap"><table><caption>Current workspace members</caption><thead><tr><th scope="col">User ID</th><th scope="col">Role</th><th scope="col">Joined</th><th scope="col">Controls</th></tr></thead><tbody>{members.map((member) => <tr key={member.user_id}><td><code>{member.user_id}</code>{member.user_id === ctx.actor.userId ? " (you)" : ""}</td><td><StatusChip tone={member.role === "owner" ? "positive" : "neutral"}>{member.role}</StatusChip></td><td>{new Date(member.created_at).toLocaleDateString()}</td><td>{admin && member.user_id !== ctx.actor.userId ? <div className="table-actions"><form action={updateMemberRoleAction}><input type="hidden" name="userId" value={member.user_id} /><label className="sr-only" htmlFor={`role-${member.user_id}`}>Role for {member.user_id}</label><select id={`role-${member.user_id}`} name="role" defaultValue={member.role}>{roles.filter((role) => role !== "owner" || ctx.actor.role === "owner").map((role) => <option value={role} key={role}>{role}</option>)}</select><SubmitButton className="button button-secondary button-small" pendingLabel="Saving…">Save role</SubmitButton></form><form action={removeMemberAction}><input type="hidden" name="userId" value={member.user_id} /><SubmitButton className="button button-danger button-small" pendingLabel="Removing…">Remove</SubmitButton></form></div> : "—"}</td></tr>)}</tbody></table></div></section>
    {admin ? <section className="workspace-card workspace-section-spaced"><SectionHeading title="Invitations" description="Open, accepted, expired and revoked invitations remain auditable." />{invitations.length ? <div className="table-wrap"><table><caption>Workspace invitations</caption><thead><tr><th scope="col">Email</th><th scope="col">Role</th><th scope="col">Expires</th><th scope="col">State</th><th scope="col">Control</th></tr></thead><tbody>{invitations.map((invitation) => { const open = !invitation.accepted_at && !invitation.revoked_at && new Date(invitation.expires_at) > new Date(); const state = invitation.accepted_at ? "accepted" : invitation.revoked_at ? "revoked" : open ? "open" : "expired"; return <tr key={invitation.id}><td>{invitation.email}</td><td>{invitation.role}</td><td>{new Date(invitation.expires_at).toLocaleString()}</td><td><StatusChip tone={state === "open" ? "warning" : state === "accepted" ? "positive" : "neutral"}>{state}</StatusChip></td><td>{open ? <form action={revokeInvitationAction}><input type="hidden" name="invitationId" value={invitation.id} /><SubmitButton className="button button-secondary button-small" pendingLabel="Revoking…">Revoke</SubmitButton></form> : "—"}</td></tr>;})}</tbody></table></div> : <p>No invitations have been created.</p>}</section> : null}
  </>;
}
