import Link from "next/link";
import { EmptyState, Notice, PageHeader, SectionHeading, StatCard, StatusChip } from "@/components/product-ui";
import { getIntelligenceAnalytics, listBrands, listProjects, listQuestions } from "@/lib/db";
import type { MetricValue, ProviderKey } from "@/types/contracts";
import { providerKeys } from "@/types/contracts";
import { getDashboardContext } from "../_context";

export const metadata = { title: "Analytics" };
const metricLabels: Record<MetricValue["key"], string> = { capture_coverage: "Capture coverage", mention_rate: "Mention rate", mention_share: "Mention share", recommendation_rate: "Recommendation rate", recommendation_share: "Recommendation share", first_choice_rate: "First-choice rate", owned_citation_rate: "Owned citation rate", evidence_support_rate: "Evidence support rate" };
const metricKeys = Object.keys(metricLabels) as MetricValue["key"][];
const percent = (value: number | null) => value === null ? "Not calculated" : `${(value * 100).toFixed(1)}%`;
const isoStart = (value?: string) => value && /^\d{4}-\d{2}-\d{2}$/u.test(value) ? `${value}T00:00:00.000Z` : undefined;
const isoEnd = (value?: string) => value && /^\d{4}-\d{2}-\d{2}$/u.test(value) ? `${value}T23:59:59.999Z` : undefined;

export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string; provider?: string; market?: string; locale?: string; questionType?: string; persona?: string; competitorId?: string; metric?: string }> }) {
  const [ctx, query] = await Promise.all([getDashboardContext(), searchParams]);
  const projects = await listProjects(ctx);
  const project = projects[0];
  if (!project) return <><PageHeader eyebrow="Analytics" title="A metric is only as honest as its denominator." description="Create a project before calculating a cohort." /><EmptyState title="No project" description="Analytics requires a tenant-scoped project." actionHref="/dashboard/setup" actionLabel="Create project" /></>;
  const provider = providerKeys.includes(query.provider as ProviderKey) ? query.provider as ProviderKey : undefined;
  const selectedMetric = metricKeys.includes(query.metric as MetricValue["key"]) ? query.metric as MetricValue["key"] : "recommendation_share";
  const [questions, brands] = await Promise.all([listQuestions(ctx, project.id), listBrands(ctx, project.id)]);
  const questionTypes = [...new Set(questions.map((question) => question.question_type))].toSorted();
  const personas = [...new Set(questions.flatMap((question) => question.persona ? [question.persona] : []))].toSorted();
  const competitors = brands.filter((brand) => brand.role === "competitor");
  const analytics = await getIntelligenceAnalytics(ctx, project.id, { from: isoStart(query.from), to: isoEnd(query.to), providers: provider ? [provider] : undefined, markets: query.market ? [query.market] : undefined, locales: query.locale ? [query.locale] : undefined, questionTypes: query.questionType ? [query.questionType] : undefined, personas: query.persona ? [query.persona] : undefined, competitorIds: query.competitorId ? [query.competitorId] : undefined });
  const metric = analytics.metrics[selectedMetric];
  const included = new Set(metric.includedIds);
  const exclusions = new Map(metric.exclusions.map((item) => [item.id, item.reason]));
  return <>
    <PageHeader eyebrow="Analytics" title="A metric is only as honest as its denominator." description="Every value below is calculated from tenant-scoped observation, classification, review and citation records using metric version 2." actions={<div className="page-actions"><Link className="button button-secondary button-small" href="/dashboard/analytics/evidence">Evidence</Link><Link className="button button-small" href="/dashboard/analytics/competitors">Competitors</Link></div>} />
    <section className="workspace-card"><SectionHeading title="Cohort filters" description="Dates are UTC. Empty filters include every stored record for this project." /><form method="get" className="product-form"><div className="form-grid"><div className="field"><label htmlFor="analytics-from">From</label><input id="analytics-from" name="from" type="date" defaultValue={query.from} /></div><div className="field"><label htmlFor="analytics-to">To</label><input id="analytics-to" name="to" type="date" defaultValue={query.to} /></div><div className="field"><label htmlFor="analytics-provider">Provider</label><select id="analytics-provider" name="provider" defaultValue={provider ?? ""}><option value="">All providers</option>{providerKeys.map((key) => <option key={key} value={key}>{key.replaceAll("_", " ")}</option>)}</select></div><div className="field"><label htmlFor="analytics-market">Market</label><input id="analytics-market" name="market" defaultValue={query.market} /></div><div className="field"><label htmlFor="analytics-locale">Locale</label><input id="analytics-locale" name="locale" defaultValue={query.locale} /></div><div className="field"><label htmlFor="analytics-question-type">Question type</label><select id="analytics-question-type" name="questionType" defaultValue={query.questionType ?? ""}><option value="">All question types</option>{questionTypes.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></div><div className="field"><label htmlFor="analytics-persona">Persona</label><select id="analytics-persona" name="persona" defaultValue={query.persona ?? ""}><option value="">All personas</option>{personas.map((value) => <option key={value} value={value}>{value}</option>)}</select></div><div className="field"><label htmlFor="analytics-competitor">Competitor cohort</label><select id="analytics-competitor" name="competitorId" defaultValue={query.competitorId ?? ""}><option value="">All tracked cohorts</option>{competitors.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></div><div className="field"><label htmlFor="analytics-metric">Drill-down metric</label><select id="analytics-metric" name="metric" defaultValue={selectedMetric}>{metricKeys.map((key) => <option key={key} value={key}>{metricLabels[key]}</option>)}</select></div></div><div className="form-footer"><p>{analytics.records.length} observation record{analytics.records.length === 1 ? "" : "s"} match this cohort.</p><button className="button button-small" type="submit">Apply filters</button></div></form></section>
    {analytics.limitations.filter((item) => item.severity !== "info").map((item) => <Notice key={item.code} title={item.severity === "blocking" ? "Comparison blocked" : "Cohort warning"} tone={item.severity === "blocking" ? "critical" : "warning"}><p>{item.message}</p></Notice>)}
    <section className="stat-grid stat-grid-three" aria-label="Intelligence metrics">{metricKeys.map((key, index) => { const value = analytics.metrics[key]; return <StatCard key={key} label={metricLabels[key]} value={percent(value.value)} detail={`${value.numerator} / ${value.denominator} · v${value.metricVersion}`} tone={index === 0 ? "accent" : "default"} />; })}</section>
    <section className="workspace-card workspace-section-spaced"><SectionHeading title={`${metricLabels[selectedMetric]} record lineage`} description={`${metric.formula}. Cohort ${metric.cohortKey}.`} />{!analytics.records.length ? <EmptyState title="No matching attempts" description="Change the cohort filters or request a monitoring run." /> : <div className="table-wrap"><table><caption>Included and excluded capture attempts for {metricLabels[selectedMetric]}</caption><thead><tr><th scope="col">Captured or attempted</th><th scope="col">Provider</th><th scope="col">Question</th><th scope="col">Metric treatment</th><th scope="col">Lineage</th></tr></thead><tbody>{analytics.records.map((record) => <tr key={record.recordId}><td>{new Date(record.capturedAt).toLocaleString()}</td><td>{record.provider}<br /><small>{record.model ?? "surface not recorded"}</small></td><td>{record.prompt ?? record.questionId}</td><td>{included.has(record.recordId) ? <StatusChip tone="positive">Included</StatusChip> : <><StatusChip tone="warning">Excluded</StatusChip><br /><small>{exclusions.get(record.recordId)?.replaceAll("_", " ") ?? "not in denominator"}</small></>}</td><td><Link className="text-link" href={`/dashboard/runs/${record.runId}`}>Open run</Link></td></tr>)}</tbody></table></div>}</section>
    <section className="workspace-card workspace-section-spaced"><SectionHeading title="Cohort contract" description="Exact dimensions stored in this calculation." /><div className="quality-grid">{[["Runs", analytics.cohort.runIds.length], ["Question sets", analytics.cohort.questionSetIds.length], ["Providers", analytics.cohort.providers.join(", ") || "None"], ["Models or surfaces", analytics.cohort.models.join(", ") || "None"], ["Markets", analytics.cohort.markets.join(", ") || "None"], ["Locales", analytics.cohort.locales.join(", ") || "None"]].map(([label, value]) => <article key={label}><h3>{label}</h3><p>{value}</p></article>)}</div>{analytics.limitations.filter((item) => item.severity === "info").map((item) => <p className="workspace-footnote" key={item.code}>{item.message}</p>)}</section>
  </>;
}
